language: java

cache:
  directories:
    - ${HOME}/.m2/repository
    - ${HOME}/downloads

env:
  global:
    - MAVEN_WRAPPER: 0
    - COVERAGE_BUILD: 0
    - CODECOV_VERSION: 2.0.15
    - PIP_RETRY: 10
    - CURL_CONNECT_TIMEOUT: 300
    - CURL_MAX_TIME: 1800
    - CURL_RETRY: 10
    - CURL_RETRY_DELAY: 10
    - DEPENDENCIES_HOME: ${HOME}/dependencies
    - DOWNLOADS_HOME: ${HOME}/downloads

matrix:
  include:
    # OpenJDK 11
    - dist: bionic
      env: COVERAGE_BUILD=1
      jdk: openjdk11
      addons:
        apt:
          packages:
            - "python3-pip"
    # OpenJDK 11 with Maven Wrapper
    - dist: bionic
      env: MAVEN_WRAPPER=1
      jdk: openjdk11
    # OpenJDK 12
    - dist: bionic
      jdk: openjdk12
    # OpenJDK 8
    - dist: trusty
      jdk: openjdk8
    # Oracle JDK 8
    - dist: trusty
      jdk: oraclejdk8
    # Oracle JDK 9
    - dist: trusty
      jdk: oraclejdk9
    # OpenJDK 10
    - dist: bionic
      jdk: openjdk10
    # Oracle JDK 11
    - dist: trusty
      jdk: oraclejdk11
    # Amazon Corretto 8
    - dist: bionic
      env: CUSTOM_JDK=amazon-corretto CUSTOM_JDK_VERSION=8.222.10.1
    # Amazon Corretto 11
    - dist: bionic
      env: CUSTOM_JDK=amazon-corretto CUSTOM_JDK_VERSION=11.0.4.11.1
    # Azul Systems Zulu 8
    - dist: bionic
      env: CUSTOM_JDK=azul-zulu CUSTOM_JDK_VERSION=8.0.222
    # Azul Systems Zulu 11
    - dist: bionic
      env: CUSTOM_JDK=azul-zulu CUSTOM_JDK_VERSION=11.0.4
    # AdoptOpenJDK 8
    - dist: bionic
      env: CUSTOM_JDK=AdoptOpenJDK CUSTOM_JDK_VERSION=8u222b10
    # AdoptOpenJDK 11
    - dist: bionic
      env: CUSTOM_JDK=AdoptOpenJDK CUSTOM_JDK_VERSION=11.0.4_11

install: source ./scripts/travis/install.sh

script: source ./scripts/travis/build.sh

after_success: source ./scripts/travis/codecov.sh
