image: Visual Studio 2017

platform:
  - x64

environment:
  MAVEN_WRAPPER: 0
  COVERAGE_BUILD: 0
  PIP_RETRY: 10
  CODECOV_VERSION: 2.0.15

  matrix:
    - JDK_VERSION: 8
      COVERAGE_BUILD: 1
    - JDK_VERSION: 11
      MAVEN_WRAPPER: 1
    - JDK_VERSION: 12
    - JDK_VERSION: 10
    - JDK_VERSION: 11

cache:
  - C:\Users\appveyor\.m2\repository -> appveyor.yml

install:
  - ps: .\scripts\appveyor\install.ps1

build_script:
  - ps: .\scripts\appveyor\build.ps1

after_build:
  - ps: .\scripts\appveyor\codecov.ps1

test: false

artifacts:
  - path: 'rle\target\*.jar'
    name: 'RLE JAR'
  - path: 'rle\target\*.exec'
    name: 'RLE JaCoCo stats'
  - path: 'jewelery-and-stones\target\*.jar'
    name: 'Jewelery & Stones JAR'
  - path: 'jewelery-and-stones\target\*.exec'
    name: 'Jewelery & Stones JaCoCo stats'
  - path: 'max-sequence-len\target\*.jar'
    name: 'Max Sequence Length JAR'
  - path: 'max-sequence-len\target\*.exec'
    name: 'Max Sequence Length JaCoCo stats'
  - path: 'deduplicate\target\*.jar'
    name: 'Duplicate Remover JAR'
  - path: 'deduplicate\target\*.exec'
    name: 'Duplicate Remover JaCoCo stats'
  - path: 'robot\target\*.jar'
    name: 'Robot JAR'
  - path: 'robot\target\*.exec'
    name: 'Robot JaCoCo stats'
  - path: 'bracket-builder\target\*.jar'
    name: 'Bracket Sequence Builder JAR'
  - path: 'bracket-builder\target\*.exec'
    name: 'Bracket Sequence Builder JaCoCo stats'
